### Numpy Mastery Assignment
- Answer all questions
- Submission : 20th September 2022

In [2]:
import numpy as np


1. Create a 1D array of numbers from 0 to 9

In [3]:
numbers = np.arange(0,10)
numbers

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

2. Create a 3x3 numpy of all True 

In [4]:
true_three = np.full((3,3), True)
true_three

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

3. Create an array of numbers from 20 to 39

In [2]:
arr_1 = np.arange(20,40)
arr_1

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39])

4. Replace all odd numbers in Q3 by -1

In [5]:
arr_1 = np.arange(20,40)
arr_1[arr_1%2 != 0] =-1
arr_1

array([20, -1, 22, -1, 24, -1, 26, -1, 28, -1, 30, -1, 32, -1, 34, -1, 36,
       -1, 38, -1])

5. Create two arrays of length 10 and print out  common items in both arrays

In [11]:
arr_2 = np.arange(10,60,5)
arr_2

arr_3 = np.arange(20,40,2)
arr_3

common_values = set(arr_2).intersection(arr_3)
print(common_values)

{20, 30}


6.  Create a 5x5 identity matrix

In [12]:
arr_4 = np.identity(5)

In [13]:
arr_4

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

7. In the code cell below define and print a set of arrays defined x, y and z. The array x should be take the form [10 12 9 2 20], y should have  101  values from  10  to  20  inclusive and z should be a  2×3  array of ones.

In [15]:
x = np.array([[10,12,9,2,20]])
x


In [16]:
x

array([[10, 12,  9,  2, 20]])

In [17]:
y =np.linspace(10,20,101)
y

array([10. , 10.1, 10.2, 10.3, 10.4, 10.5, 10.6, 10.7, 10.8, 10.9, 11. ,
       11.1, 11.2, 11.3, 11.4, 11.5, 11.6, 11.7, 11.8, 11.9, 12. , 12.1,
       12.2, 12.3, 12.4, 12.5, 12.6, 12.7, 12.8, 12.9, 13. , 13.1, 13.2,
       13.3, 13.4, 13.5, 13.6, 13.7, 13.8, 13.9, 14. , 14.1, 14.2, 14.3,
       14.4, 14.5, 14.6, 14.7, 14.8, 14.9, 15. , 15.1, 15.2, 15.3, 15.4,
       15.5, 15.6, 15.7, 15.8, 15.9, 16. , 16.1, 16.2, 16.3, 16.4, 16.5,
       16.6, 16.7, 16.8, 16.9, 17. , 17.1, 17.2, 17.3, 17.4, 17.5, 17.6,
       17.7, 17.8, 17.9, 18. , 18.1, 18.2, 18.3, 18.4, 18.5, 18.6, 18.7,
       18.8, 18.9, 19. , 19.1, 19.2, 19.3, 19.4, 19.5, 19.6, 19.7, 19.8,
       19.9, 20. ])

In [20]:
z = np.ones((2,3))
z

array([[1., 1., 1.],
       [1., 1., 1.]])

8.Using the available Numpy functions on array x from problem  7 , find the average and the standard deviation of the value in this array. Redefine x as an array with all these values sorted in numerical order.

In [21]:
x = np.array([[10,12,9,2,20]])
x

array([[10, 12,  9,  2, 20]])

In [22]:
np.mean(x)


10.6

In [23]:
np.std(x)

5.782732917920384

In [24]:
np.sort(x)

array([[ 2,  9, 10, 12, 20]])

9. Create a 10x10 array with random values and find the minimum and maximum values

In [31]:
arr_5 = np.random.randint(100,size=(10,10))
arr_5

array([[33, 79, 50, 81, 42, 43, 86, 40, 83, 91],
       [39, 60,  7, 95, 94, 51, 92, 64, 98, 52],
       [33, 27, 92, 60, 10, 55,  4, 26, 98, 41],
       [83, 91, 18, 86, 88, 14, 96, 41, 13,  1],
       [76, 66, 50, 26, 84, 36,  3, 43, 67, 69],
       [59, 25, 75,  4, 57, 64, 93, 15,  3, 43],
       [ 7, 85, 64, 98, 97, 97,  6, 44, 51, 15],
       [46, 85, 85, 49, 30,  5, 85, 78, 97, 56],
       [31, 32, 87, 10, 48, 53,  7, 34, 19, 89],
       [77, 58,  8, 55, 40, 12, 49, 89,  6, 91]])

In [32]:
np.max(arr_5)

98

In [33]:
np.min(arr_5)

1

10. Create a 3x3 matrix with values ranging from 0 to 8

In [36]:
arr_4 =np.arange(0,9)
arr_4

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [37]:
np.reshape(arr_4,(3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

11.  Generates an array [[1 2 3] [4 5 6]]

In [38]:
arr_6 =np.array([[1, 2, 3], [4, 5 ,6]])
arr_6

array([[1, 2, 3],
       [4, 5, 6]])

12. Generates an array [0 2.5 5 7.5 10]

In [42]:
arr_7 = np.array([ [0, 2.5, 5, 7.5, 10]])
arr_7

array([[ 0. ,  2.5,  5. ,  7.5, 10. ]])

13. Generates an 3x3 array of zeros

In [43]:
arr_7= np.zeros((3,3))
arr_7

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

14. Create array from 0.1 to 10 with 12 elements, inclusively

In [44]:
arr_8 =np.linspace(0.1,10,12)
arr_8

array([ 0.1,  1. ,  1.9,  2.8,  3.7,  4.6,  5.5,  6.4,  7.3,  8.2,  9.1,
       10. ])

15. Create a matrix with seven columns and five rows of ten(10).

In [46]:
arr_9 = np.full((7,5),10)
arr_9

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

16. What is the difference between numpy and list?

17. Create a 1D array of ones consisting of  50  values. Change the values of the array so that the values alternate between ones and zeros ie  1,0,1,0,1,0,1,0,1...  ensuring that the starting value is  1 

In [56]:
arr_10 =np.ones(51)
arr_10[1::2] =0
arr_10

array([1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
       1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.])

18. Generate a  10×10  matrix of zeros.
Make this matrix an identity matrix

In [60]:
arr_11 =np.zeros((10,10))
arr_11

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

19. Generate an array x to be a  10×10  array of zeros. Redefine its diagonal components (from left to right) to equal one

In [5]:
x = np.zeros((10,10))
np.fill_diagonal(x,1)
x

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

20. What is the dot products of this two matrix [[1,2],[3,4]] and [[5,6],[7,8]]

In [92]:
mat_1 =np.array([[1,2],[3,4]])
mat_1

array([[1, 2],
       [3, 4]])

21.  Multiply these two matrix [[1,2],[3,4]] and [[5,6],[7,8]]

In [65]:
mat_w =np.array([[1,2],[3,4]])
mat_w

array([[1, 2],
       [3, 4]])

In [66]:
mat_x =np.array([[5,6],[7,8]])
mat_x

array([[5, 6],
       [7, 8]])

In [67]:
mat_w*mat_x

array([[ 5, 12],
       [21, 32]])

In [ ]:
22. Multiply this matrix  [[1,2],[3,4]] by a  scalar value of 5

In [93]:
d=5
mat_y=np.array([[1,2], [3,4]])
mat_y

array([[1, 2],
       [3, 4]])

In [ ]:
23. A = ([[1,2]),[3,4]] and B = transpose of A. Calculate AxB

In [70]:
A= np.array([[1,2], [3,4]])
A

array([[1, 2],
       [3, 4]])

In [71]:
B= A.transpose((1,0))
B

array([[1, 3],
       [2, 4]])

In [72]:
A*B

array([[ 1,  6],
       [ 6, 16]])

24. A= [[1,2],[3,4]] and B =  [[5,6],[7,8]]. Is A x B = B x A ? Show working

In [73]:
A= np.array([[1,2], [3,4]])
A

array([[1, 2],
       [3, 4]])

In [74]:
B=np.array([[5,6],[7,8]])
B

array([[5, 6],
       [7, 8]])

In [81]:
A * B

array([[ 5, 12],
       [21, 32]])

In [76]:
B*A

array([[ 5, 12],
       [21, 32]])

25. Creates an array [[0 1 2] [3 4 5]]
- Let A = first row of the matrix
- B = second row of the matrix
- C = second column of the Matrix
- D = first row, third column of the matrix
- print A , B , C, D

In [83]:
array= np.array([[0, 1, 2], [3, 4, 5]])
array

array([[0, 1, 2],
       [3, 4, 5]])

In [85]:
A= array[0]
A

array([0, 1, 2])

In [86]:
B=array[1]
B

array([3, 4, 5])

In [89]:
C = array[:,1]
C

array([1, 4])

In [88]:
D=array[0][-1]
D

2

In [96]:
print(A,B,C,D)

[0 1 2] [3 4 5] [1 4] 2
